services:
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: splitify
      POSTGRES_PASSWORD: splitify_password
      POSTGRES_DB: splitify
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./db:/var/lib/postgresql
    ports:
      - 5432:5432
