services:
  website:
    restart: unless-stopped
    image: ghcr.io/domysh/splitify
    ports:
      - 127.0.0.1:80:8080
    depends_on:
      - postgres
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: splitify
      POSTGRES_PASSWORD: splitify_password
      POSTGRES_DB: splitify
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./db:/var/lib/postgresql
